### ISSUE TITLE
Bug can() and cannot()

### ISSUE THREAD

**Issue by code-beans** [jakesgordon/javascript-state-machine#146]
given that a state has a transition where `to` is a function pointer the function will be executed,  e.g. 
```
{name : 'next', from : 'mystate', to : function () {
    foo();
    return 'nextState';
}} 
```
Now when `fsm.can('next')` is called, `foo()` will be executed which in my understanding it shouldn't.
This looks related to #133 as well.

**Comment by Leestex** [comment]
Hi @code-beans 

It seems like you are trying to use `to` function in an incorrect way here.
The idea of having a function instead of defining an explicit target state name is useful in some cases, but by design it should not mutate any data.

In your specific case you should use [lifecycle events](https://github.com/jakesgordon/javascript-state-machine/blob/master/docs/lifecycle-events.md) to run the `foo` function.

Keep in mind that the `to` function should only define a target state is. It should not have any side effects, which `foo()` call is.

So the transition should look like this:
```js
{ name: 'next', from: 'mystate', to: 'nextState' }
```

And lifecycle event handler:
```js
onEnterNextState: function () {
  foo();
}
```

If you have to dynamically define a target state, you can use a function:

```js
{
  name: 'next',
  from: 'mystate',
  to: function () {
    if (condition) {
       return 'nextState';
    } else {
       return 'anotherState';
    }
  }
}
```

**Comment by code-beans** [comment]
@Leestex I see. Thanks. Maybe this should go into the docs somewhere.
